on: [push]

jobs:
    deploy_job:
         runs-on: ubuntu-latest
         name: deploy
         steps:
             - name: Checkout
               uses: actions/checkout@v2
             - name: Deploy file
               uses: wlixcc/SFTP-Deploy-Action@v1.2.4
               with:
                 username: gabi_86.5453801d
                 server: msr3079.minestrator.com
                 port: 2022
                 local_path: './*'
                 remote_path: '/plugins/Skript/scripts/'
                 sftp_only: true
                 password: ${{ secrets.FTP_PASSWORD }}
                 
                 
