name: CI-SFTP
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
            name: dist
            path: dist
      - name: Download artifact
        uses: actions/download-artifact@main
      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          METHOD: sftp
          FTP_USERNAME: tnt_man268.5453801d
          FTP_SERVER: msr3079.minestrator.com
          PORT: 2022 # default is 22
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          
          
          # will put all file under this path
          LOCAL_DIR: ./ # default is ./*
          # files will copy to under remote_path
          REMOTE_DIR: /home/plugins/Skript/scripts/
          
