name: CI-SFTP
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
    deploy_job:
         runs-on: ubuntu-latest
         name: deploy
         steps:
             - name: Checkout
               uses: actions/checkout@v2
             - name: Deploy file
               uses: wlixcc/SFTP-Deploy-Action@v1.2.4
               with:
                 username: tnt_man268.5453801d
                 server: msr3079.minestrator.com
                 port: 2022
                 local_path: './*'
                 remote_path: '/home/plugins/Skript/scripts/'
                 sftp_only: true
                 password: ${{ secrets.FTP_PASSWORD }}
