name: RCON Test

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  rcon_test:
    runs-on: ubuntu-latest
    name: RCON Test
    steps:
      - name: RCON Connection
        uses: Plagiatus/RCON-Action@v0.2
        with:
          server: '0.0.0.0'
          port: '25575'
          password: 'test'
          commands: '["say hi", "tps", "list"]'
